---
- name: Install and Configure Apache HTTP Server
  hosts: webservers
  become: true
  tasks:
    - name: Install httpd package
      yum:
        name: httpd
        state: present

    - name: Start and enable httpd service
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Copy index.html file
      copy:
        src: /path/to/your/index.html # Replace with the path to your index.html file
        dest: /var/www/html/index.html
        owner: apache
        group: apache
        mode: '0644'


